# Generated by Django 5.2.2 on 2026-03-20 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_enrollement_delete_enrollemt'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MembsershipPlan',
            new_name='MembershipPlan',
        ),
    ]
