# Generated by Django 5.2.2 on 2026-03-27 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0007_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='PhoneNumber',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
